#!/usr/bin/env bash
# Preference Inversion Experiment: do(Preference = ¬Preference)
#
# For each model, generates responses using the inverted-preference dataset
# under profile_only and profile_retrieval settings, then evaluates them.
# The original (non-inverted) results already exist from generate_all_settings.sh.
#
# After this script finishes, compare original vs inverted responses to measure
# whether model framing tracks preference direction (causal attribution).
set -euo pipefail

cd "$(dirname "$0")/.."

CONDA_BASE="$(conda info --base 2>/dev/null || echo "$HOME/miniconda3")"
# shellcheck source=/dev/null
source "${CONDA_BASE}/etc/profile.d/conda.sh"
conda activate personalization_risk

LIMIT=200
GEN_SCRIPT="scripts/generator/generate.py"
EVAL_SCRIPT="scripts/evaluator/evaluator.py"
JUDGE_MODEL="gpt-4o"
JUDGE_PROVIDER="openai"

# Inverted dataset (generated by scripts/analysis/preference_inversion.py)
INVERTED="data/sycophantic_bias/inverted_seed200_sycophantic_bias_framing.json"

# Settings to test (base is not meaningful for inversion since there's no profile)
SETTINGS=(profile_only profile_retrieval)

mkdir -p logs

# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------

gen() {
    local setting="$1" model="$2" tag="$3" provider="${4:-}" thinking="${5:-}"
    local out="output/generate/sycophantic_bias_inverted/${setting}/${setting}_${tag}_${LIMIT}.json"

    if [[ -f "$out" ]]; then
        echo "[SKIP] $out already exists"
        return 0
    fi

    echo ""
    echo "==> [GEN] setting=$setting  model=$model  tag=$tag"
    local args=(
        --dataset "$INVERTED"
        --setting "$setting"
        --candidate-model "$model"
        --limit "$LIMIT"
        --workers 16
        --out "$out"
    )
    [[ -n "$provider" ]] && args+=(--provider "$provider")
    [[ "$setting" == "profile_retrieval" ]] && args+=(--router-model "$model")
    [[ -n "$thinking" ]] && args+=(--thinking-budget "$thinking")

    python -W ignore "$GEN_SCRIPT" "${args[@]}" 2>/dev/null
}

# ---------------------------------------------------------------------------
# Evaluation
# ---------------------------------------------------------------------------

eval_job() {
    local setting="$1" tag="$2"
    local in_file="output/generate/sycophantic_bias_inverted/${setting}/${setting}_${tag}_${LIMIT}.json"
    local out_file="output/eval/sycophantic_bias_inverted/${setting}/eval_${setting}_${tag}_${LIMIT}.json"

    # Use the ORIGINAL base responses for framing comparison
    local base_file="output/generate/sycophantic_bias/base/base_${tag}_${LIMIT}.json"

    if [[ ! -f "$in_file" ]]; then
        echo "[MISSING] $in_file — skipping eval"
        return 0
    fi

    echo ""
    echo "==> [EVAL] setting=$setting  model=$tag"
    local args=(
        --input "$in_file"
        --judge-model "$JUDGE_MODEL"
        --risk-type "sycophantic_bias_framing"
        --workers 8
        --out "$out_file"
    )
    [[ -n "$JUDGE_PROVIDER" ]] && args+=(--judge-provider "$JUDGE_PROVIDER")
    [[ -f "$base_file" ]] && args+=(--base-file "$base_file")

    python -W ignore "$EVAL_SCRIPT" "${args[@]}" 2>/dev/null
}

# ---------------------------------------------------------------------------
# Provider groups (run in parallel)
# ---------------------------------------------------------------------------

run_group() {
    local log="$1"; shift
    local models=("$@")
    {
        for model_entry in "${models[@]}"; do
            IFS='|' read -r model tag provider thinking <<< "$model_entry"
            for setting in "${SETTINGS[@]}"; do
                gen "$setting" "$model" "$tag" "$provider" "$thinking"
            done
        done

        # Evaluate after generation
        for model_entry in "${models[@]}"; do
            IFS='|' read -r model tag provider thinking <<< "$model_entry"
            for setting in "${SETTINGS[@]}"; do
                eval_job "$setting" "$tag"
            done
        done
    } 2>&1 | tee "$log"
}

OPENAI_MODELS=(
    "gpt-5.4-mini|gpt5_4_mini|openai|"
)
ANTHROPIC_MODELS=(
    "claude-haiku-4-5-20251001|claude_haiku_4_5||"
)
GOOGLE_MODELS=(
    "gemini-2.5-flash|gemini_2_5_flash||1000"
)

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  Preference Inversion Experiment                            ║"
echo "║  Dataset: $INVERTED"
echo "║  Settings: ${SETTINGS[*]}"
echo "║  Models: gpt-5.4-mini, claude-haiku-4.5, gemini-2.5-flash  ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

run_group "logs/inv_openai.log"    "${OPENAI_MODELS[@]}"    &
PID_OPENAI=$!
run_group "logs/inv_anthropic.log" "${ANTHROPIC_MODELS[@]}" &
PID_ANTHROPIC=$!
run_group "logs/inv_google.log"    "${GOOGLE_MODELS[@]}"    &
PID_GOOGLE=$!

EXIT=0
wait "$PID_OPENAI"    || { echo "[ERROR] openai group failed";    EXIT=1; }
wait "$PID_ANTHROPIC" || { echo "[ERROR] anthropic group failed"; EXIT=1; }
wait "$PID_GOOGLE"    || { echo "[ERROR] google group failed";    EXIT=1; }

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "Generation + Evaluation done. Exit code: $EXIT"
echo ""
echo "Next step: run the inversion analysis to compare original vs inverted:"
echo "  python scripts/analysis/compare_inversion.py \\"
echo "    --original-dir output/eval/sycophantic_bias/ \\"
echo "    --inverted-dir output/eval/sycophantic_bias_inverted/ \\"
echo "    --out output/analysis/preference_inversion_results.json"
echo "════════════════════════════════════════════════════════════════"
exit "$EXIT"
